In [171]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split

#  House pricing analysis

Cieľ: na základe dát ako ulica na ktorej sa byt nachádza, vybavenie bytu, susedstvo, atď. **odhadnite cenu bytu**.

Dátový súbor obsahuje 2919 záznamom a 81 premenných (po spojení tréningového a testovacieho súboru, z dôvodu rovnakej úpravy dát. Pred predikciou bol opäť rozdelený).

Zvolený postup: 
1. zoznámenie sa s dátami (predchádzajúci notebook)
2. vysporiadanie sa s chýbajúcimi pozorovaniami:
- odstránenie niektorých záznamov (ak chábalo jediné porozovanie z celého datasetu)
- nahradenie "missing values" (numerical) pomocou mediánu (nie je najlepšia technika. Chcel som použiť nahradenie pomocou KNN algorytmu, avšak mal som problém s načítaním knižnice)
- ponechanie "missing values" z dôvodu, že by aj oni mohli priniesť informáciu pre odhad ceny
3. "One hot encoding" kategorických premenných 
4. Zvolenie správnej Neurónovej siete pre odhad ceny
5. Finálny odhad

In [172]:
df1 = pd.read_csv('C:/Users/zamec/Desktop/M7DataSp/cvičenie 1/house-prices-advanced-regression-techniques/HousepricesAll.csv')

In [173]:
df1.shape

(2919, 81)

Zistenie počtu chábajúcich pozorovaní pre numerické premenné. 
- Ak sa v celom stĺpci nachádzal len jeden chábajúci záznam, tak som vymazal len daný riadok. Takto som prišiel o 3 záznamy.
- V prípade premennej MaSVnArea so tiež odstránil 23 zázánamov.
- Premenné LotFrontageArea, GarageYrBlt - som chábajúce pozorovania nahradil mediánom z daného stĺpcu

In [174]:
integerDrop = []

for i in range(df1.shape[1]):
    if (df1.dtypes[i] == 'int64' or df1.dtypes[i] == 'float64') and df1.isna().sum()[i]:
        
        print("In Column %s is %d missing values" %(df1.columns[i],df1.isna().sum()[i]))
        
        if df1.isna().sum()[i] < 24:
            integerDrop.append(df1.columns[i])

In Column LotFrontage is 486 missing values
In Column MasVnrArea is 23 missing values
In Column BsmtFinSF1 is 1 missing values
In Column BsmtFinSF2 is 1 missing values
In Column BsmtUnfSF is 1 missing values
In Column TotalBsmtSF is 1 missing values
In Column BsmtFullBath is 2 missing values
In Column BsmtHalfBath is 2 missing values
In Column GarageYrBlt is 159 missing values
In Column GarageCars is 1 missing values
In Column GarageArea is 1 missing values

In [175]:
df1 = df1.dropna(axis = 0,subset = integerDrop)
df1.shape

(2893, 81)

Premenné ktoré neobsahovali viac ako 90% záznamov (niektoré až 99%).

In [176]:
df1.drop(["PoolQC","Fence","MiscFeature","Alley","FireplaceQu"], axis = 1, inplace = True)

.

Skontrolovanie počtu katogórií kategorických premenných a uvažovnie nad možnosťou spojiť tie, ktoré obsahujú malý počet pozorovaní do kategórie **others**. Nakoniec som kategórie ponechal v pôvodnom tvare.

In [177]:
categoricalColumns = []
for name in df1.columns:
    
    if df1.dtypes[name] == "O":
        categoricalColumns.append(name)
        print( "The column %s has: %d categories" %(name,len(df1[name].unique())))

The column MSZoning has: 6 categories
The column Street has: 2 categories
The column LotShape has: 4 categories
The column LandContour has: 4 categories
The column Utilities has: 3 categories
The column LotConfig has: 5 categories
The column LandSlope has: 3 categories
The column Neighborhood has: 25 categories
The column Condition1 has: 9 categories
The column Condition2 has: 8 categories
The column BldgType has: 5 categories
The column HouseStyle has: 8 categories
The column RoofStyle has: 6 categories
The column RoofMatl has: 8 categories
The column Exterior1st has: 16 categories
The column Exterior2nd has: 17 categories
The column MasVnrType has: 5 categories
The column ExterQual has: 4 categories
The column ExterCond has: 5 categories
The column Foundation has: 6 categories
The column BsmtQual has: 5 categories
The column BsmtCond has: 5 categories
The column BsmtExposure has: 5 categories
The column BsmtFinType1 has: 7 categories
The column BsmtFinType2 has: 7 categories
The column Heating has: 6 categories
The column HeatingQC has: 5 categories
The column CentralAir has: 2 categories
The column Electrical has: 6 categories
The column KitchenQual has: 5 categories
The column Functional has: 8 categories
The column GarageType has: 7 categories
The column GarageFinish has: 4 categories
The column GarageQual has: 6 categories
The column GarageCond has: 6 categories
The column PavedDrive has: 3 categories
The column SaleType has: 10 categories
The column SaleCondition has: 6 categories

In [178]:
medians = df1.loc[:,['LotFrontage','GarageYrBlt']].median()

df1['LotFrontage'] = df1['LotFrontage'].replace(np.nan,medians[0])
df1['GarageYrBlt'] = df1['GarageYrBlt'].replace(np.nan,medians[1])

df1 = df1.replace(np.nan,'None')

Kategorizácia kategorických premenných pre potreby NN.

In [179]:
df1 = pd.get_dummies(df1, columns=categoricalColumns)

In [187]:
#split na tie co budem odhadovat a testovacie a treningove 
dfPrediction = df1.loc[df1['SalePrice'] == 0 ]
dfTestTrain = df1.loc[df1['SalePrice'] != 0 ]

labels = dfTestTrain['SalePrice'].array
dfTestTrain.drop(['SalePrice'], axis = 1, inplace = True)

C:\Users\zamec\Anaconda3\lib\site-packages\pandas\core\frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [191]:
labels = np.array(labels)

In [192]:
X_train, X_test, y_train, y_test = train_test_split(dfTestTrain, labels, train_size = 0.8, random_state = 20)


print("Train shape is: (%d,%d)" %(X_train.shape[0],X_train.shape[1]))
print("Test shape is: (%d,%d)" %(X_test.shape[0],X_test.shape[1]))
print("Train target shape is: (%d,)" %(y_train.shape[0]))
print("Train target shape is: (%d,)" %(y_test.shape[0]))

Train shape is: (1161,288)
Test shape is: (291,288)
Train target shape is: (1161,)
Train target shape is: (291,)

Po bližšom nahliadnutí na rôznorodosť variability dát (min, max, mean), som sa rozhodol pre škálovanie dát pomocou **MinmaxScalet**, čo je typická technika pri danom probléme. Pomocou neho môžme výrazne pomôcť k rýchlejšej konvergenicii neurénovej siete.

In [193]:
X_train.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_New,SaleType_None,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
count,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,...,1161.000000,1161.0,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000,1161.000000
mean,730.233419,57.734711,69.619294,10507.368648,6.091301,5.587425,1970.985357,1985.050818,104.810508,439.101637,...,0.079242,0.0,0.002584,0.874246,0.072351,0.003445,0.009475,0.009475,0.823428,0.081826
std,422.298740,42.973953,22.688933,10732.347731,1.388475,1.136911,30.321592,20.711150,182.101218,456.458050,...,0.270233,0.0,0.050789,0.331714,0.259181,0.058621,0.096917,0.096917,0.381470,0.274218
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,365.000000,20.000000,60.000000,7446.000000,5.000000,5.000000,1953.000000,1967.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
50%,730.000000,50.000000,68.000000,9350.000000,6.000000,5.000000,1972.000000,1994.000000,0.000000,384.000000,...,0.000000,0.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
75%,1098.000000,70.000000,78.000000,11478.000000,7.000000,6.000000,2000.000000,2004.000000,168.000000,704.000000,...,0.000000,0.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [194]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

## Výber architektúry neurónovej siete

Nakoniec som zvolil architektúru typu **288-64-64-32-1** aj z dôvodu aby nebola príliš robustná a NN sa rýchlo nepreučila. 
- Stálo by zváženie skúsenie rôznych druhov aktivačných funkcii ako **sigmoid, tanh...** avšak k najlepšej MAE (priemernej absolútnej chybe) som sa dostal pomocou nasledovnej NN.

In [195]:
from keras.models import Sequential, load_model
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D,BatchNormalization
from keras import optimizers



model = Sequential()
model.add(Dense(64, activation='relu',input_shape=(X_train.shape[1],)))
model.add(Dense(64, activation='selu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])

model.summary()

Model: "sequential_21"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_79 (Dense)             (None, 64)                18496
_________________________________________________________________
dense_80 (Dense)             (None, 64)                4160
_________________________________________________________________
dense_81 (Dense)             (None, 32)                2080
_________________________________________________________________
dense_82 (Dense)             (None, 1)                 33
=================================================================
Total params: 24,769
Trainable params: 24,769
Non-trainable params: 0
_________________________________________________________________

.

Najnižšie s MAE som sa dostal k hodnote **15268** , tj. priemerný rozdiel medzi reálnou a odhadnoutou cenou testovacieho súboru bolo 15000 dolárov. To je stále vysoký rozdiel a určite by sa táto hodnota dala ešte znížiť použitím odlišnej NN.

In [196]:
models_data = model.fit(X_train, y_train, 
          batch_size=1, epochs=150, verbose=0,validation_data=(X_test,y_test))

In [163]:
model.save(r"C:\Users\zamec\Desktop\M7DataSp\cvičenie 1\FirstModel.h5")

In [201]:
model = load_model(r"C:\Users\zamec\Desktop\M7DataSp\cvičenie 1\FirstModel.h5")

In [202]:
dfPrediction.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_None,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,SalePrice
1460,1461,20,80.0,11622,5,6,1961,1961,0.0,468.0,...,0,0,1,0,0,0,0,1,0,115372.742188
1461,1462,20,81.0,14267,6,6,1958,1958,108.0,923.0,...,0,0,1,0,0,0,0,1,0,100577.031250
1462,1463,60,74.0,13830,5,5,1997,1998,0.0,791.0,...,0,0,1,0,0,0,0,1,0,189002.937500
1463,1464,60,78.0,9978,6,6,1998,1998,20.0,602.0,...,0,0,1,0,0,0,0,1,0,201688.890625
1464,1465,120,43.0,5005,8,5,1992,1992,0.0,263.0,...,0,0,1,0,0,0,0,1,0,189872.453125

In [203]:
dfPrediction.drop(['SalePrice'], axis = 1, inplace = True)

C:\Users\zamec\Anaconda3\lib\site-packages\pandas\core\frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [204]:
dfPrediction1 = scaler.transform(dfPrediction)

In [205]:
SalePrice = []

for i in range(dfPrediction.shape[0]):
    
    x = np.expand_dims(dfPrediction1[i,:], axis=0)
    
    SalePrice.append(model.predict(x)[0][0])
    
dfPrediction['SalePrice'] = SalePrice

C:\Users\zamec\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

**Finálny súbor s predikovanými hodntami zo súboru test.csv**

In [206]:
dfPrediction

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_None,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,SalePrice
1460,1461,20,80.0,11622,5,6,1961,1961,0.0,468.0,...,0,0,1,0,0,0,0,1,0,122324.062500
1461,1462,20,81.0,14267,6,6,1958,1958,108.0,923.0,...,0,0,1,0,0,0,0,1,0,100377.789062
1462,1463,60,74.0,13830,5,5,1997,1998,0.0,791.0,...,0,0,1,0,0,0,0,1,0,191525.187500
1463,1464,60,78.0,9978,6,6,1998,1998,20.0,602.0,...,0,0,1,0,0,0,0,1,0,203431.796875
1464,1465,120,43.0,5005,8,5,1992,1992,0.0,263.0,...,0,0,1,0,0,0,0,1,0,187347.437500
1465,1466,60,75.0,10000,6,5,1993,1994,0.0,0.0,...,0,0,1,0,0,0,0,1,0,177151.640625
1466,1467,20,68.0,7980,6,7,1992,2007,0.0,935.0,...,0,0,1,0,0,0,0,1,0,185451.781250
1467,1468,60,63.0,8402,6,5,1998,1998,0.0,0.0,...,0,0,1,0,0,0,0,1,0,169553.843750
1468,1469,20,85.0,10176,7,5,1990,1990,0.0,637.0,...,0,0,1,0,0,0,0,1,0,188047.375000
1469,1470,20,70.0,8400,4,5,1970,1970,0.0,804.0,...,0,0,1,0,0,0,0,1,0,129595.726562
1470,1471,120,26.0,5858,7,5,1999,1999,0.0,1051.0,...,0,0,1,0,0,0,0,1,0,167980.156250
1471,1472,160,21.0,1680,6,5,1971,1971,504.0,156.0,...,0,0,0,0,0,0,0,1,0,103725.140625
1472,1473,160,21.0,1680,5,5,1971,1971,492.0,300.0,...,0,0,1,0,0,0,0,1,0,99929.187500
1473,1474,160,24.0,2280,6,6,1975,1975,0.0,514.0,...,0,0,1,0,0,0,0,1,0,149327.015625
1474,1475,120,24.0,2280,7,6,1975,1975,0.0,0.0,...,0,0,1,0,0,0,0,1,0,107917.882812
1475,1476,60,102.0,12858,9,5,2009,2010,162.0,0.0,...,0,0,0,0,0,0,0,0,1,366081.000000
1476,1477,20,94.0,12883,8,5,2009,2010,256.0,0.0,...,0,0,0,0,0,0,0,0,1,254496.984375
1477,1478,20,90.0,11520,9,5,2005,2005,615.0,110.0,...,0,0,1,0,0,0,0,1,0,285515.968750
1478,1479,20,79.0,14122,8,5,2005,2006,240.0,28.0,...,0,0,1,0,0,0,0,1,0,293357.125000
1479,1480,20,110.0,14300,9,5,2003,2004,1095.0,1373.0,...,0,0,1,0,0,0,0,1,0,502564.843750
1480,1481,60,105.0,13650,8,5,2002,2002,232.0,578.0,...,0,0,1,0,0,0,0,1,0,339926.093750
1481,1482,120,41.0,7132,8,5,2006,2006,178.0,24.0,...,0,0,1,0,0,0,0,1,0,208559.921875
1482,1483,20,100.0,18494,6,5,2005,2005,0.0,0.0,...,0,0,1,0,0,0,0,1,0,177226.593750
1483,1484,120,43.0,3203,7,5,2006,2006,14.0,16.0,...,0,0,1,0,0,0,0,1,0,174269.187500
1484,1485,80,67.0,13300,7,5,2004,2004,0.0,326.0,...,0,0,1,0,0,0,0,1,0,188158.390625
1485,1486,60,63.0,8577,7,5,2004,2004,0.0,0.0,...,0,0,1,0,0,0,0,1,0,191796.515625
1486,1487,60,60.0,17433,8,5,1998,1998,114.0,0.0,...,0,0,1,0,0,0,0,1,0,360203.312500
1487,1488,20,73.0,8987,8,5,2005,2006,226.0,0.0,...,0,0,1,0,0,0,0,1,0,254799.125000
1488,1489,20,92.0,9215,7,5,2009,2010,0.0,0.0,...,0,0,0,0,0,0,0,0,1,201800.859375
1489,1490,20,84.0,10440,6,5,2005,2005,0.0,1414.0,...,0,0,1,0,0,0,0,1,0,249749.656250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2889,2890,30,50.0,7030,4,6,1925,1950,0.0,0.0,...,0,0,1,0,0,0,0,1,0,84646.562500
2890,2891,50,75.0,9060,6,5,1957,1957,327.0,0.0,...,0,0,1,0,0,0,0,1,0,143646.796875
2891,2892,30,69.0,12366,3,5,1945,1950,0.0,0.0,...,0,0,1,1,0,0,0,0,0,10380.210938
2892,2893,190,50.0,9000,5,6,1951,1951,0.0,0.0,...,0,0,1,1,0,0,0,0,0,70803.359375
2893,2894,50,60.0,8520,3,5,1916,1950,0.0,0.0,...,0,0,1,0,0,0,0,1,0,9954.350586
2894,2895,120,41.0,5748,8,5,2005,2006,473.0,1573.0,...,0,0,0,0,0,0,0,0,1,373215.250000
2895,2896,120,44.0,3842,8,5,2004,2005,186.0,1564.0,...,0,0,1,0,0,0,0,1,0,307908.875000
2896,2897,20,69.0,23580,6,6,1979,1979,0.0,776.0,...,0,0,1,0,0,0,0,1,0,207167.734375
2897,2898,90,65.0,8385,6,5,1978,1978,0.0,0.0,...,0,0,1,0,0,0,0,1,0,150749.859375
2898,2899,20,70.0,9116,8,5,2001,2001,0.0,0.0,...,0,0,1,0,0,0,0,1,0,196468.750000
2899,2900,80,140.0,11080,6,6,1975,1975,257.0,576.0,...,0,0,1,0,0,0,0,1,0,169858.140625
2900,2901,20,68.0,50102,6,5,1958,1958,0.0,909.0,...,0,0,1,0,0,1,0,0,0,216741.906250
2901,2902,20,68.0,8098,6,5,2000,2000,0.0,1136.0,...,0,0,1,0,0,0,0,1,0,170972.390625
2902,2903,20,95.0,13618,8,5,2005,2006,198.0,1350.0,...,0,0,0,0,0,0,0,0,1,304491.937500
2903,2904,20,88.0,11577,9,5,2005,2006,382.0,1455.0,...,0,0,0,0,0,0,0,0,1,352491.343750
2904,2905,20,125.0,31250,1,3,1951,1951,0.0,0.0,...,0,0,1,0,0,0,0,1,0,69484.304688
2905,2906,90,78.0,7020,7,5,1997,1997,200.0,1243.0,...,0,0,1,0,0,0,0,1,0,194010.906250
2906,2907,160,41.0,2665,5,6,1977,1977,0.0,0.0,...,0,0,1,0,0,0,0,1,0,110542.390625
2907,2908,20,58.0,10172,5,7,1968,2003,0.0,441.0,...,0,0,1,0,0,0,0,1,0,131934.718750
2908,2909,90,68.0,11836,5,5,1970,1970,0.0,149.0,...,0,0,1,0,0,0,0,1,0,146884.062500
2909,2910,180,21.0,1470,4,6,1970,1970,0.0,522.0,...,0,0,1,0,0,0,0,1,0,75311.789062
2910,2911,160,21.0,1484,4,4,1972,1972,0.0,252.0,...,0,0,1,0,0,0,0,1,0,83661.273438
2911,2912,20,80.0,13384,5,5,1969,1979,194.0,119.0,...,0,0,1,0,0,0,0,1,0,155055.906250
2912,2913,160,21.0,1533,4,5,1970,1970,0.0,408.0,...,0,0,1,1,0,0,0,0,0,73108.296875
2913,2914,160,21.0,1526,4,5,1970,1970,0.0,0.0,...,0,0,1,0,0,0,0,1,0,75868.890625
2914,2915,160,21.0,1936,4,7,1970,1970,0.0,0.0,...,0,0,1,0,0,0,0,1,0,83547.046875
2915,2916,160,21.0,1894,4,5,1970,1970,0.0,252.0,...,0,0,1,1,0,0,0,0,0,75575.523438
2916,2917,20,160.0,20000,5,7,1960,1996,0.0,1224.0,...,0,0,1,1,0,0,0,0,0,169371.984375
2917,2918,85,62.0,10441,5,5,1992,1992,0.0,337.0,...,0,0,1,0,0,0,0,1,0,113434.023438
2918,2919,60,74.0,9627,7,5,1993,1994,94.0,758.0,...,0,0,1,0,0,0,0,1,0,207151.734375